#!/bin/sh

APPDIR=$(dirname "$0")
java  -Djava.library.path="$APPDIR:$APPDIR/lib" -cp "$APPDIR/lib/core.jar:$APPDIR/lib/javase.jar:$APPDIR/lib/sketch_130418a.jar:$APPDIR/lib/core.jar:$APPDIR/lib/jogl-all.jar:$APPDIR/lib/gluegen-rt.jar:$APPDIR/lib/jogl-all-natives-linux-i586.jar:$APPDIR/lib/gluegen-rt-natives-linux-i586.jar:$APPDIR/lib/gstreamer-java.jar:$APPDIR/lib/jna.jar:$APPDIR/lib/video.jar" sketch_130418a "$@"
